---
title: "STAT 2857A -- Lecture 10 Examples and Exercises"
format: 
  pdf: default
  docx: default
knitr: 
  opts_chunk:
    fig.align: center
    echo: false
    warning: false
    message: false
    digits: 2
prefer-html: true
---

```{r}
# Load packages
library(tidyverse)
library(patchwork)
library(knitr)
library(kableExtra)
library(broom)
```

## Example 10.1
What is the probability of each of these events?

a) You toss a fair coin 5 times and it lands heads side up 3 times?
b) You draw 5 cards from a standard deck \textit{with replacemnt} and draw 3 red cards?
c) You guess the answer to 5 true or false questions on a quiz and get three correct.
d) You roll a fair die 5 times and the number shown is odd on 3 rolls. 

## Example 10.2

Approximately 79\% of the world's population has brown eyes \footnote{\url{https://www.worldatlas.com}}. Suppose that we sample 5 people from the population at random and record their eye-colour as brown or not brown. Let $X$ represent the number of people in our sample with brown eyes. Is this a binomial experiment?

## Example 10.3

A standard roulette wheel has 37 pockets in which the ball may land. Of these, 18 pockets are red, 18 are black, and 1 is green. Suppose that you place \$1 bets that the ball will land in a black pocket on 20 consecutive games. Let $X$ be the number of times you win.

a) Why is this a binomial experiment?
b) What is the distribution of $X$?
c) What is the pmf of $X$?
d) What is the probability that you win exactly half the games?
e) What is the probability that you win more than half the games?
f) What are the mean, variance, and standard deviation of $X$?
g) Let \$$v$ be the amount you win on a \$1 bet if the ball lands in a black pocket. What value of \$$v$ makes this a fair game?

## Exercise 10.1

The shooting percentage in hockey records the percentage of shots on goal taken in a season on which a player scores. The highest shooting percentage in the 2023-2024 NHL season, 24.5\%, was claimed by Sam Reinhart of the Florida Panthers. Let $S$ be the number of goals Sam scores on his first 200 shots on net in the 2024-2025 season. Assume that his shooting percentage stays the same.

a) Explain why it makes sense to consider this a binomial experiment.
b) State the distribution of $S$.
c) What is the pmf of $S$?
d) What are the expected value and standard deviation of $S$?
e) What is the probability that Sam scores at least 50 goals?
