---
title: "STAT 2857A -- Lecture 3 Examples and Exercises"
subtitle: "Solutions -- Revised 18/09/24"
format: 
  pdf: 
   include-in-header: 
    - text: |
        \usepackage{mathtools}
knitr: 
  opts_chunk:
    fig.align: center
    echo: false
    warning: false
    message: false
    digits: 2
---

```{r}
# Load packages
library(tidyverse)
library(patchwork)
library(knitr)
library(kableExtra)
library(broom)
```

## Example 3.1

a) Let $A$ be the event that you do not roll a 3. We can represent the outcome as an ordered triplet of the numbers 1,2,3 indicating the outcome on each roll. There are $3 \times 3 \times 3=3^3=27$ possible outcomes. There are $2 \times 2 \times 2=8$ that do not contain a 3. Hence, the probability of not rolling a 3 on any of the rolls is 
$$
P(A)=8/27=.296.
$$

b) Let $B$ be the event that the sum is greater than 4. In this case, it is easier to compute the probability of $B'$ and then apply the complement rule. The sum is greater than 4 if any of the rolls is 3 or there are more than two 2s. This means that the only outcomes with a sum of four or less are $(1,1,1)$, $(1,1,2)$, $(1,2,1)$, and $(2,1,1)$. Hence
$$
P(B')=4/27=.148
$$
and
$$
P(B)=23/27=.852.
$$

c) The event of interest is $A \cup B$. Applying the union rule
$$
P(A \cup B) =P(A) + P(B) - P(A \cap B).
$$
Note that $A \cap B$ is the set of outcomes such that no roll is a 3 and the sum is greater than 4. There are 4 such outcomes $(1,2,2)$, $(2,1,2)$, $(2,2,1)$, and $(2,2,2)$. Hence
$$
P(A \cup B)=8/27 + 23/27 - 4/27=27/27=1.00.
$$
Note that we can also see this by applying De Morgan's rules. Consider that $(A \cup B)'=A'\cap B'$. This is the set of outcomes that contain a 3 but have a sum less than or equal to 5. This set is empty (there are no outcomes satisfying this constraint) because the sum must be at least 5 is there are any 3s. Hence
$$
P((A \cup B)')=0/27 = 0.00
$$
so
$$
P(A \cup B)=1-P((A \cup B)')=1.00.
$$

## Example 3.2

a) This is a combination because it does not matter in what order you receive the cards. All that matters is what 5 cards you end up with. The total number of hands is
$$
\prescript{}{52}C_5={52 \choose 5}=\frac{52!}{5!47!}=2,598,960.
$$

b) This is a permutation because the order does matter. The number of ways for four people to line up is
$$
\prescript{}{4}P_4=\frac{4!}{0!} = 24.
$$

c) Players in the lotto 6/49 choose 6 of the numbers 1 through 49 without replacement. They win if they pick enough numbers correctly, and the order does not matter. This is a combination. The number of possible choices is
$$
\prescript{}{49}C_{6}={49 \choose 6}=13,983,816.
$$
c) The order that students are assigned to teams does not matter. The total is
$$
\prescript{}{150}C_{10}={150 \choose 10}\approx 1.170 \times 10^{15}.
$$

d) In this case, the order does not matter when we choose which 20 students will be in the lines, but it does matter when we choose the position of the students in the lines. There are many ways to solve this problem. Here is one:
  
    - There are $\prescript{}{30}C_{10}={30 \choose 10}=30,045,015$ to choose the students for the first line.
    - Given that the students for the first line have been chose, there are $\prescript{}{20}C_{10}={20 \choose 10}=184,756$ ways to choose the students for the second line. 
    - There are then $\prescript{}{10}P_{10}=10! = 3,628,800$ to order the students in each line. 
    - This means that there are
    $$
    30,045,015 \times 184,756 \times 3,628,800^2\approx 7.31 \times 10^{25}
    $$
    ways to create 2 lines of 20 students from a class of 30.
  
    Alternatively, we could say:
    - There are $\prescript{}{30}C_{20}={20 \choose 20}=30,045,015$ ways to choose the 20 students in the lines.
    - There are $\prescript{}{20}C_{20}P=20! = 2.433 \times 10^{18}$ ways to order the 20 students.
    - This means that there are
    $$
    30,045,015 \times 2.433 \times 10^{18} = 7.31 \times 10^{25}
    $$
    ways to create 2 lines of 20 students from a class of 30.
  
## Example 3.3

a) Let $A$ be the event that you are dealt a royal flush (in any order). There are 2,598,960 hands ignoring order, as shown in Example 2.2. Ignoring order, there are only 4 hands that provide a royal flush. You can have a royal flush in clubs, diamonds, hearts, or spades. Hence, the probability is
$$
P(A)=4/2,598,960=1.54 \times 10^{-6}.
$$
b) Let $B$ be the event that you are dealt a royal flush (10, J, Q, K, A of the same suit) in order. We know from Example 3.2 that there are 2,598,960 possible hands ignoring order. Each hand can be dealt in $\prescript{}{5}P_{5}=5! = 120$ ways. Hence, there are $2,598,960 \times 120=311,875,200$ possible hands if we don't ignore order. We can also compute this directly as $\prescript{}{52}P_{5}=52!/47! = 311,875,200$. 

    Again, there are only 4 ways to be dealt a royal flush in order. Hence, the probability of this event is
$$
P(A)=4/311,875,200\approx 1.28 \times 10^{-8}.
$$

c) Let $C$ be the event that you are dealt a pair. We can answer this question by thinking about the events that need to happen in order:

    - First, you need to pick one value for the pair. There are $\prescript{}{13}C_{1}=13$ ways to do this.
    - Then, you need to pick two of the suits of that value. There are $\prescript{}{4}C_{2}6$ possible pairs of cards with the selected value.
    - Finally, you need to choose the remaining three cards. However, there are some restrictions. The value of these cards can't match the value chosen in the first step, and they can't match each other's values. First, we need to choose the values of the remaining cards. There are 12 values left and we need to pick three, which gives $\prescript{}{12}C_{3}=220$ possible combinations. For each of these values, there are $\prescript{}{4}C_{1}=4$ possible cards. 
    - The total number of hands that result in a pair is
  $$
  13 \times 6 \times 220 \times 4 \times 4 \times 4=1098240.
  $$
  
    Hence, the probability of being dealt a pair is
  $$
  P(C)=1,098,240/2,598,960=.4226.  
  $$
  
d) Again, there are many ways to answer this question. Here is one. Let $D$ be the event of dealing a full house:

    - First, we need to pick the two values. There are $\prescript{}{13}C_{2}={13 \choose 2}=78$ ways to do this.
    - Next, we must choose which value will have three cards. There are $\prescript{}{2}C_{1}={2 \choose 1}=2$ ways to do this.
    - Finally, we must choose 3 or the 4 suits for the first value and 2 of the 4 suits for the second. There are $\prescript{}{4}C_{3} \times \prescript{}{4}C_{2}={4 \choose 3}{4 \choose 2}=24$ ways to do this.
    - The total number of ways to deal a full house is
  $$
  78 \times 2 \times 24=3744.
  $$
  Hence, the probability of being dealt a full house is
  $$
  P(D)=3744/2,598,960=.0014.
  $$
  
## Exercise 3.1

a) Let $A$ be the event that you are dealt a flush. There are ${4 \choose 1}=4$ ways to choose the suit and ${13 \choose 5}=1287$ ways to choose 5 cards from that suit. Hence
$$
P(A)=(4 \times 1287)/2,598,960=.00198.
$$

b) Let $B$ be the event that you are dealt two pair. There are ${13 \choose 2}=78$ ways to pick the values of the two pairs and ${11 \choose 1}=11$ ways to pick the final value. There are ${4 \choose 2}=6$ ways to pick the cards for each of the first two values and ${4 \choose 1}=4$ to pick the card for the third value. Hence
$$
P(B)=(78 \times 11 \times 6 \times 6 \times 4)/2,598,960=.0475.
$$

c) Let $C$ be the event that you are dealt three of a kind. There are ${13 \choose 1}=13$ ways to choose the first suit and ${12 \choose 2}=66$ ways to choose the second and third. Then there are ${4 \choose 3}=4$ ways to choose 3 cards from the first suit and ${4 \choose 1}=4$ ways to choose 1 card each from the second and third. Hence
$$
P(C)=(13 \times 66 \times 4 \times 4 \times 4)/2,598,960=.0211.
$$