---
title: "STAT 2857A -- Lecture 12 Examples and Exercises"
format: 
  pdf: default
  docx: default
knitr: 
  opts_chunk:
    fig.align: center
    echo: false
    warning: false
    message: false
    digits: 2
prefer-html: true
---

```{r}
# Load packages
library(tidyverse)
library(patchwork)
library(knitr)
library(kableExtra)
library(broom)
```

## Example 12.1

According to the book ``United States Water Law: An Introduction'' by John W.~Johnson, heavy rain falls at about 495 drops per second per metre square. Let $X$ be the number of rain drops that falls in one metre square in $t$ seconds.

a) What is the distribution of $X$?
b) What is the pmf of $X$?
c) What are the mean and variance of $X$?
d) How does the shape of the distribution vary with $t$?

## Example 12.2

In lecture 4, we showed that the probability that a randomly selected person is colour blind is about .04512. Let $X$ be the number of colour blind students in a class of 100.
  
a) What is the distribution of $X$?
b) What are the mean and variance of $X$?
c) What is the probability that the class contains more than 5 students who are colour blind?
d) Approximate the distribution of $X$ by a Poisson and repeat the questions above. 
e) Do you think the Poisson approximation is appropriate?

## Exercise 12.1

One gram of Uranium-235 contains $2.35 \times 10^{21}$ atoms. Each atom has probability $9.85 \times 10^{-10}$ of decaying in one year. Let $X$ be the number of atoms that decay in 1 year. You may assume that atoms decay independently of one another.
  
a) What is the distribution of $X$?
b) What are the mean and variance of $X$?
c) What is the probability that the number of decays in one year is greater than the mean?
d) Approximate the distribution of $X$ by a Poisson and repeat the questions above. 
e) Do you think the Poisson approximation is appropriate?