---
title: "STAT 2857A -- Lecture 15 Examples and Exercises"
subtitle: "Solutions"
format: 
  pdf: 
   include-in-header: 
    - text: |
        \usepackage{mathtools}
knitr: 
  opts_chunk:
    fig.align: center
    echo: false
    warning: false
    message: false
    digits: 2
---

```{r}
## Load packages
library(tidyverse)
library(knitr)
library(latex2exp)
```

## Example 15.1

a) The first mean of $X$ is:
$$
\begin{aligned}
  E(X)
  &=\int_{-\infty}^{\infty}u f(u)~du\\
  &=\int_0^1 u(2u) ~du\\
  &=\left[\frac{2u^3}{3}\right]_0^1\\
  &=2/3\\
\end{aligned}
$$

b) There are two ways to compute the variance. First, we can compute it directly
$$
\begin{aligned}
\sigma_X^2
&=E[(X-\mu_X)^2]\\
&=E[(X-2/3)^2]\\
&=\int_{0}^1 (x-2/3)^2 \cdot 2x ~dx\\
&=\int_0^1 2x^3 -8/3x^2 + 8/9 x ~dx\\
&=\left[\frac{2x^4}{4}-\frac{8x^3}{9} + \frac{8x^2}{18}\right]_0^1\\
&=\frac{1}{2} - \frac{8}{9} + \frac{4}{9}\\
&=1/18.
\end{aligned}
$$
Alternatively, we can use the shortcut formula
$$
\sigma_X^2=E(X^2)-E(X)^2.
$$
Then:
$$
\begin{aligned}
E(X^2)
  &=\int_0^1 u^2(2u) ~du\\
  &=\left[\frac{2u^4}{4}\right]_0^1\\
  &=1/2\\
\end{aligned}
$$
Applying the shortcut formula we get
$$
  \sigma^2_X=\frac{1}{2}-\left(\frac{2}{3}\right)^2=\frac{1}{18}.
$$
c) If we were to repeatedly drop an object from a height of 1~m on Emperor Zurg's home planet and stop it at a randomly selected time between 0 and 1 second then the average distance the objects has fallen would be very close to 2/3~m and get closer and closer the more times we drop the object. 

d) In this case, $Y$ is a linear transformation of $X$. Hence
$$
  E(Y)=E(39.73 X)=39.73 E(X)=\frac{39.73(2)}{3}=26.4867
$$
and
$$
  V(Y)=V(39.73 X)=39.73^2 V(X)=\frac{39.73^2 (1)}{18}=87.693.
$$
The mean and variance of $Y$ are $26.5$ inches and $87.7$ inches squared.

e) We need to apply the formula for the variance of a function directly since $Z$ is not a linear function of $X$. First, we get
$$
\begin{aligned}
\mu_Z=E(Z)
&=\int_0^1 x^2 \cdot 2x ~dx\\
&=\int_0^1 2x^3~dx\\
&=\left[\frac{x^4}{2}\right]_0^1\\
&=1/2.
\end{aligned}
$$
Then
$$
\begin{aligned}
E(Z^2)
&=\int_0^1 x^4 \cdot 2x ~dx\\
&=\int_0^1 2x^5~dx\\
&=\left[\frac{x^6}{3}\right]_0^1\\
&=1/3.
\end{aligned}
$$
Applying the shortcut formula
$$
\sigma^2_Z=E(Z^2)-E(Z)^2=\frac{1}{3}-\left(\frac{1}{2}\right)^2=\frac{1}{12}.
$$

## Exercise 15.2

a) We need to show that:

    1. $f(x)\geq 0$ for all $x$, and
    2. $\int_{-\infty}^{\infty}f(x)~dx=1$
    
    To show the first property, note that $f(x)=0$ for all $x<0$ or $x>2$. Then for $0\leq x \leq 2$, $f(x)=3/4[2x-x^2]>0$. Hence, $f(x) \geq 0$ for all $x \in \Re$.
    
    Then
    $$
    \begin{aligned}
    \int_{-\infty}^{\infty}f(x)~dx
    &=\int_0^2 \frac{3}{4}[2x-x^2]~dx\\
    &=\frac{3}{4}\left[x^2 - \frac{x^3}{3}\right]_0^2\\
    &=\frac{3}{4}\left[4-\frac{8}{3}\right]\\
    &=1.
    \end{aligned}
    $$
    Hence, $f(x)$ is a valid pdf.
    
b) Note that
$$
\begin{aligned}
E(X)
&=\int_0^2 x \cdot \frac{3}{4}[2x-x^2]~dx\\
&=\frac{3}{4}\int_0^2 2x^2-x^3~dx\\
&=\frac{3}{4}\left[\frac{2x^3}{3}-\frac{x^4}{4}\right]_0^2\\
&=\frac{3}{4}\left[\frac{16}{3}-\frac{16}{4}\right]\\
&=1
\end{aligned}
$$
and
$$
\begin{aligned}
E(X^2)
&=\int_0^2 x^2 \cdot \frac{3}{4}[2x-x^2]~dx\\
&=\frac{3}{4}\int_0^2 2x^3-x^4~dx\\
&=\frac{3}{4}\left[\frac{2x^4}{4}-\frac{x^5}{5}\right]_0^2\\
&=\frac{3}{4}\left[\frac{32}{3}-\frac{32}{5}\right]\\
&=6/5.
\end{aligned}
$$
Then
$$
\mu_X=E(X)=1
$$
and
$$
\sigma_X^2=E(X^2)-E(X)^2=\frac{6}{5}-1=\frac{1}{5}.
$$

c) Note that $Y$ is a linear function of $X$. Then
$$
\mu_Y=3\mu_X+2=5
$$
and
$$
\sigma^2_Y=3^2\sigma^2_X=\frac{9}{5}=2.2.
$$

d) Note that $Z$ is not a linear function of $X$, so we must compute the mean and variance from the definitions. We have
$$
\begin{aligned}
E(Z)
&=E(X^2)\\
&=\frac{6}{5}
\end{aligned}
$$
from the result above. Further,
$$
\begin{aligned}
E(Z^2) 
&=E(X^4)\\
&=\int_0^2 x^4 \cdot \frac{3}{4}[2x-x^2]~dx\\
&=\frac{3}{4}\int_0^2 2x^5-x^6~dx\\
&=\frac{3}{4}\left[\frac{2x^6}{6}-\frac{x^7}{7}\right]_0^2\\
&=\frac{3}{4}\left[\frac{64}{3}-\frac{128}{7}\right]\\
&=\frac{16}{7}.
\end{aligned}
$$
Hence
$$
\mu_Z=E(Z)=\frac{6}{5}
$$
and
$$
\sigma^2_Z-E(Z^2)-E(Z)^2=\frac{16}{7}-\left(\frac{6}{5}\right)^2=\frac{38}{35}=1.08571.
$$