---
title: "STAT 2857A -- Lecture 23a Examples and Exercises"
format: 
  pdf: 
   include-in-header: 
    - text: |
        \usepackage{mathtools}
knitr: 
  opts_chunk:
    fig.align: center
    echo: false
    warning: false
    message: false
    digits: 2
---
```{r}
## Load packages
library(tidyverse)
library(knitr)
library(latex2exp)
library(kableExtra)
library(readxl)

## Options
opt_bkp <- options
options(digits = 4)
```

Suppose that $X$ and $Y$ are random variables with joint pdf:
$$
f(x,y)=c(1-(x+y)), \quad  0< x <1, 0<y<1, x+y<1.
$$
The contours of the pdf look like this:
```{r}
#| fig-width: 4
#| fig-height: 4
mydf <- crossing(x = seq(0,2,length = 101),
                 y = seq(0,2,length = 101)) |> 
  mutate(f = (1-(abs(x) + abs(y))) * (abs(x) + abs(y) < 1))

ggplot(data=mydf,aes(x=x,y=y,z=f)) +
  xlab("x") +
  ylab("y") +
  geom_hline(yintercept = 0) + 
  geom_vline(xintercept = 0) +
  geom_contour()
```

a) Find the value of $c$.
b) Find the marginal pdf of $X$ and $Y$.
c) Find the conditional pdf of $X|Y=y$. 
d) Find the conditional mean and variance of $X|Y=y$.
e) It can be shown that
$$
E(X)=E(Y)=1/4
$$
and
$$
V(X)=V(Y)=3/80.
$$
What are the covariance and correlation of $X$ and $Y$?