---
title: "STAT 2857A -- Lecture 23a Examples and Exercises"
subtitle: "Solutions"
format: 
  pdf: 
   include-in-header: 
    - text: |
        \usepackage{mathtools}
knitr: 
  opts_chunk:
    fig.align: center
    echo: false
    warning: false
    message: false
    digits: 2
---
```{r}
## Load packages
library(tidyverse)
library(knitr)
library(kableExtra)
library(latex2exp)
library(readxl)

## Options
opt_bkp <- options
options(digits = 3)
```

a) We know that 
$$
\frac{1}{c}=\int_{-\infty}^{\infty} \int_{-\infty}^{\infty} \frac{f(x,y)}{c} ~dy ~dx
$$
in order that the joint pdf integrates to 1. To compute the integral, we need to find the bounds of integration. I'll consider $y$ as this inner variable of integration. The second constraint states that $0<y<1$ and the third constraint implies that $y<1-x$. Putting these together we have that $0<y<1-x$. The overall bounds on $x$ are then $0<x<1$ as stated. Hence:
$$
\begin{aligned}
\int_{-\infty}^{\infty} \int_{-\infty}^{\infty} \frac{f(x,y)}{c} ~dy ~dx
&=\int_0^1 \int_0^{1-x} 1-(x + y) ~dy ~dx\\
&=\int_0^1 \left[y - xy + \frac{y^2}{2}\right]_0^{1-x} ~dx\\
&=\int_0^1 \frac{1-2x+x^2}{2}~dx\\
&=\frac{1}{2}\left[x-x^2+\frac{x^3}{3}\right]_0^1\\
&=\frac{1}{6}.
\end{aligned}
$$
Hence, $c=6$ and the full joint pdf is
$$
f(x,y)=6(1-(x + y)), 0<x<1, 0<y<1-x.
$$

b) The marginal pdf of $X$ is defined to be
$$
\begin{aligned}
f_X(x)&=\int_{-\infty}^{\infty} f(x,y)~dy\\
&=\int_{0}^{1-x} 6(1-(x+y)) ~dy\\
&=6\left[y-xy-\frac{y^2}{2}\right]_0^{1-x}\\
&=6\left((1-x) - x(1-x)-\frac{(1-x)^2}{2}\right)\\
&=3(1-x)^2, \quad 0<x<1.
\end{aligned}
$$
The marginal pdf of $Y$ is defined to be
$$
f_Y(y)=\int_{-\infty}^{\infty} f(x,y)~dx\\
$$
However, we need to find the bounds on $x$ as a function of $y$. The third constraint implies that $x<1-y$. Combining this with the first constraint, we have that $0<x<1-y$. Then
$$
f_Y(y)=\int_{0}^{1-y} 6(1-(x+y)) ~dx
$$
Note that this is exactly the same integral as above, except that we've switched the roles of $x$ and $y$. We will do exactly the same operations to solve the integral. Hence, the marginal pdf will be the same except the argument (the variable in the function) will be replaced with $y$. We say that "by symmetry":
$$
f_Y(y)=3(1-y)^2, \quad 0<y<1.
$$

c) By definition, the conditional pdf of $X|Y=y$ is
$$
\begin{aligned}
f_{X|Y}(x|y)
&=\frac{f(x,y)}{f_Y(y)}\\
&=\frac{6(1 - (x+y))}{3(1-x)^2}\\
&=2\frac{1-(x+y)}{(1-x)^2}.
\end{aligned}
$$
However, as always, we must include the support. In this case, $x$ must be positive and less than $1-y$ in order that $x+y<1$. Hence, the conditional pdf is
$$
f_{X|Y}(x|y)=2\frac{1-(x+y)}{(1-y)^2}, \quad 0<x<1-y.
$$
d) The conditional mean of $X|Y=y$ is
$$
\begin{aligned}
E(X|Y=y)
&=\int_{-\infty}^{\infty} x f_{X|Y}(x|y)~dx\\
&=\int_0^{1-y} \frac{2x(1-(x+y))}{(1-y)^2}~dx\\
&=\frac{2}{(1-y)^2} \int_0^{1-y} x(1-y)-x^2 ~dx\\
&=\frac{2}{(1-y)^2} \left[\frac{x^2}{2}(1-y)-\frac{x^3}{3}\right]_0^{1-y}\\
&=\frac{2}{(1-y)^2} \left[\frac{(1-y)^3}{2}-\frac{(1-y)^3}{3}\right]\\
&=\frac{1-y}{3}.
\end{aligned}
$$
Similarly
$$
\begin{aligned}
E(X^2|Y=y)
&=\int_{-\infty}^{\infty}x^2 f_{X|Y}(x|y)~dx\\
&=\int_0^{1-y} \frac{2x^2(1-(x+y))}{(1-y)^2}~dx\\
&=\frac{2}{(1-y)^2} \int_0^{1-y} x^2(1-y)-x^3 ~dx\\
&=\frac{2}{(1-y)^2} \left[\frac{x^3}{3}(1-y)-\frac{x^4}{4}\right]_0^{1-y}\\
&=\frac{2}{(1-y)^2} \left[\frac{(1-y)^4}{3}-\frac{(1-y)^4}{4}\right]\\
&=\frac{(1-y)^2}{6}.
\end{aligned}
$$
Applying the shortcut formula the variance is
$$
\begin{aligned}
V(X)
&=E(X^2)-E(X)^2\\
&=\frac{(1-y)^2}{6}-\frac{(1-y)^2}{9}\\
&=\frac{(1-y)^2}{18}.
\end{aligned}
$$

e) The final piece of information we need to compute the covariance and correlation is 
$$
\begin{aligned}
E(XY)
&=\int_{-\infty}^{\infty}\int_{-\infty}^{\infty} xyf(x,y)~dy~dx\\
&=\int_0^1 \int_0^{1-x} 6xy(1-(x+y)) ~dy ~dx\\
&=6\int_0^1 \int_0^{1-x} x(1-x)y - xy^2 ~dy ~dx\\
&=6\int_0^1 \left[\frac{x(1-x)y^2}{2}-\frac{xy^3}{3}\right]_0^{1-x}~dx\\
&=6\int_0^1 \left(\frac{x(1-x)^3}{2}-\frac{x(1-x)^3}{3}\right)~dx\\
&=6\int_0^1 \frac{x(1-x)^3}{6}~dx\\
&=\int_0^1 \frac{x(1-x)^3} ~dx\\
&=\frac{1}{20}.
\end{aligned}
$$
Then
$$
\begin{aligned}
\mbox{Cov}(X,Y)
&=E(XY)-E(X)E(Y)\\
&=\frac{1}{20}-\frac{1}{16}\\
&=\frac{-1}{80}
\end{aligned}
$$
and
$$
\begin{aligned}
\mbox{Corr}(X,Y)
&=\frac{\mbox{Cov}(X,Y)}{\sqrt{V(X)V(Y)}}\\
&=\frac{-1/80}{3/80}\\
&=\frac{-1}{3}.
\end{aligned}
$$
The fact that the correlation is negative makes sense based on the contour plot of the joint pdf. The range of $Y$ decreases as $X$ increases. If $X=.01$, then $Y$ can take any value between $0$ and $.99$. However, if $X=.5$, then $Y$ can only take values between $0$ and $.5$, and if $X=.99$ then $Y$ can only take values between 0 and $.01$. Hence there is a negative association between the two variables. 

